version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    env_file: .env
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: '--config.file=/etc/prometheus/prometheus.yml --config.expand-env'
    ports:
      - "9090:9090"
    networks:
      - vault-net

  dashboard:
    build: .
    container_name: vault-dashboard
    depends_on:
      - prometheus
    env_file: .env
    ports:
      - "4173:4173"
    networks:
      - vault-net

networks:
  vault-net:
    driver: bridge
