version: '3.8'

services:
  dashboard:
    build: .
    container_name: vault-dashboard
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      PROMETHEUS_ADDR: ${PROMETHEUS_ADDR}
    ports:
      - "4173:4173"
