version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    command: vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200
    ports:
      - "8200:8200"
    networks:
      - vault-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - vault-net

  dashboard:
    build: .
    container_name: vault-dashboard
    depends_on:
      - vault
      - prometheus
    environment:
      VAULT_ADDR: http://vault:8200
      PROMETHEUS_ADDR: http://prometheus:9090
    ports:
      - "4173:4173"
    networks:
      - vault-net

networks:
  vault-net:
    driver: bridge
