global:
  scrape_interval: 15s

scrape_configs:
    - job_name: 'vault'
      metrics_path: /v1/sys/metrics
      params:
        format: [prometheus]
      static_configs:
        - targets: ['${PROMETHEUS_TARGET}']
